import NavBar from '../components/NavBar';
import '../app/globals.css';

export const metadata = {
  title: 'Bytown Bats',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  );
}